/**
 * Local wellbeing scoring for SAHABAT.AI.
 *
 * The original implementation called a FastAPI service running an XGBoost
 * regressor. That model was trained on synthetic data generated by a
 * deterministic PHQ-9/GAD-7-aligned formula (see risk-engine/model.py). We
 * port the formula directly here so the whole app deploys to a single
 * Vercel runtime — no Python container, no network hop.
 *
 * Exposes:
 *   - `scoreWellbeing(features)`  → pure function, 0–100 score + tier + top factors.
 *   - `computeFeatures(userId, supabase)` → derives the five features from
 *     the user's last 7 days of chats + journals.
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database, WellbeingTier } from "@/lib/supabase/types";

export type RiskFeatures = {
  sentiment_avg_7d: number;
  mood_avg_7d: number;
  sleep_avg_7d: number;
  journal_count_7d: number;
  social_engagement_7d: number;
};

export type TopFactor = {
  key: keyof RiskFeatures;
  label: string;
  direction: "low" | "high" | "healthy";
  value: number;
  contribution: number;
  copy: string;
};

export type RiskScore = {
  score: number;
  tier: WellbeingTier;
  top_factors: TopFactor[];
  model_version: string;
};

// ---------------------------------------------------------------------------
// Scoring
// ---------------------------------------------------------------------------

// Weights transcribed from risk-engine/model.py synth_dataset().
// distress = sum of contributions; wellbeing = clip(100 - distress, 0, 100).
const WEIGHTS = {
  mood: 7.0, // (7 - mood) × 7
  sentiment: 18.0, // (0.2 - sentiment) × 18
  sleep: 3.5, // |sleep - 7.5| × 3.5  (bidirectional)
  journals: 1.8, // max(0, 5 - journals) × 1.8
  social: 22.0, // (0.55 - social) × 22
} as const;

// Relative importances for the top-factor ranking. Derived from the
// maximum contribution each feature can make to distress, normalised to
// sum ≈ 1. Roughly matches the XGB feature_importances_ the Fly service
// used to return.
const FEATURE_IMPORTANCE: Record<keyof RiskFeatures, number> = {
  mood_avg_7d: 0.379,
  sentiment_avg_7d: 0.195,
  sleep_avg_7d: 0.237,
  journal_count_7d: 0.081,
  social_engagement_7d: 0.109,
};

type FeatureSpec = {
  key: keyof RiskFeatures;
  label: string;
  healthy: number;
  softMin: number;
  softMax: number;
  healthy_copy: string;
  low_copy: string;
  high_copy: string;
};

const FEATURE_SPECS: readonly FeatureSpec[] = [
  {
    key: "sentiment_avg_7d",
    label: "Sentiment",
    healthy: 0.2,
    softMin: -1,
    softMax: 1,
    healthy_copy: "Messages feel balanced to slightly positive.",
    low_copy: "Messages have leaned heavy or sad this week.",
    high_copy: "Messages are unusually bright — great signal.",
  },
  {
    key: "mood_avg_7d",
    label: "Mood",
    healthy: 7,
    softMin: 1,
    softMax: 10,
    healthy_copy: "Daily mood sits in a healthy range.",
    low_copy: "Daily mood check-ins have been low this week.",
    high_copy: "Mood check-ins are very high — hopeful sign.",
  },
  {
    key: "sleep_avg_7d",
    label: "Sleep",
    healthy: 7.5,
    softMin: 0,
    softMax: 12,
    healthy_copy: "Sleep is in a healthy 7–9 hour range.",
    low_copy: "Sleep has been running short this week.",
    high_copy: "Sleep has been unusually long — worth a look.",
  },
  {
    key: "journal_count_7d",
    label: "Check-in streak",
    healthy: 5,
    softMin: 0,
    softMax: 7,
    healthy_copy: "Consistent check-ins — keeps signals fresh.",
    low_copy: "Fewer check-ins this week; signals are thinner.",
    high_copy: "Check-ins are strong — great rhythm.",
  },
  {
    key: "social_engagement_7d",
    label: "Social engagement",
    healthy: 0.55,
    softMin: 0,
    softMax: 1,
    healthy_copy: "You've stayed connected to people this week.",
    low_copy: "Social engagement has dipped this week.",
    high_copy: "Strong connection with people around you.",
  },
] as const;

function tierFor(score: number): WellbeingTier {
  if (score >= 75) return "green";
  if (score >= 55) return "yellow";
  if (score >= 35) return "orange";
  return "red";
}

function explain(f: RiskFeatures): TopFactor[] {
  const rows = FEATURE_SPECS.map((spec) => {
    const value = f[spec.key];
    const span = Math.max(spec.softMax - spec.softMin, 1e-6);
    let deviation = 0;
    let direction: "low" | "high" | "healthy" = "healthy";

    if (spec.key === "sleep_avg_7d") {
      deviation = Math.abs(value - spec.healthy) / span;
      direction =
        deviation < 0.08 ? "healthy" : value < spec.healthy ? "low" : "high";
    } else if (value < spec.healthy) {
      deviation =
        (spec.healthy - value) / Math.max(spec.healthy - spec.softMin, 1e-6);
      direction = "low";
    }

    const importance = FEATURE_IMPORTANCE[spec.key];
    const contribution = Math.max(deviation, 0) * importance;
    const copy =
      direction === "low"
        ? spec.low_copy
        : direction === "high"
          ? spec.high_copy
          : spec.healthy_copy;

    return {
      weight: contribution,
      factor: {
        key: spec.key,
        label: spec.label,
        direction,
        value,
        contribution: 0,
        copy,
      } satisfies TopFactor,
    };
  });

  rows.sort((a, b) => b.weight - a.weight);
  const top = rows.slice(0, 3);
  const total = top.reduce((s, r) => s + r.weight, 0) || 1;
  return top.map((r) => ({
    ...r.factor,
    contribution: Math.round((r.weight / total) * 1000) / 1000,
  }));
}

export async function scoreWellbeing(
  features: RiskFeatures,
): Promise<RiskScore> {
  let distress = 0;
  distress += (7 - features.mood_avg_7d) * WEIGHTS.mood;
  distress += (0.2 - features.sentiment_avg_7d) * WEIGHTS.sentiment;
  distress += Math.abs(features.sleep_avg_7d - 7.5) * WEIGHTS.sleep;
  distress += Math.max(0, 5 - features.journal_count_7d) * WEIGHTS.journals;
  distress += (0.55 - features.social_engagement_7d) * WEIGHTS.social;

  const score = Math.round(Math.max(0, Math.min(100, 100 - distress)));
  return {
    score,
    tier: tierFor(score),
    top_factors: explain(features),
    model_version: "ts-heuristic-0.1.0",
  };
}

// ---------------------------------------------------------------------------
// Derive features from Supabase
// ---------------------------------------------------------------------------

const DAY_MS = 24 * 60 * 60 * 1000;

const HEALTHY_DEFAULTS: RiskFeatures = {
  sentiment_avg_7d: 0.2,
  mood_avg_7d: 7,
  sleep_avg_7d: 7.5,
  journal_count_7d: 0,
  social_engagement_7d: 0.55,
};

const avg = (xs: number[], fallback: number) =>
  xs.length === 0 ? fallback : xs.reduce((a, b) => a + b, 0) / xs.length;

export async function computeFeatures(
  userId: string,
  supabase: SupabaseClient<Database>,
): Promise<RiskFeatures> {
  const since = new Date(Date.now() - 7 * DAY_MS).toISOString();

  const [journalsRes, chatsRes] = await Promise.all([
    supabase
      .from("journals")
      .select("mood_score, sleep_hours, sentiment_score, created_at")
      .eq("user_id", userId)
      .gte("created_at", since),
    supabase
      .from("chats")
      .select("sentiment, role, created_at")
      .eq("user_id", userId)
      .gte("created_at", since),
  ]);

  const journals = journalsRes.data ?? [];
  const chats = chatsRes.data ?? [];

  const moodValues = journals
    .map((j) => j.mood_score)
    .filter((x): x is number => typeof x === "number");
  const sleepValues = journals
    .map((j) => j.sleep_hours)
    .filter((x): x is number => typeof x === "number");

  const chatSentiments = chats
    .map((c) => c.sentiment)
    .filter((x): x is number => typeof x === "number");
  const journalSentiments = journals
    .map((j) => j.sentiment_score)
    .filter((x): x is number => typeof x === "number");
  const allSentiments = [...chatSentiments, ...journalSentiments];

  const userChats = chats.filter((c) => c.role === "user").length;
  const engagement = Math.max(0, Math.min(1, userChats / 28));

  return {
    sentiment_avg_7d: Number(
      avg(allSentiments, HEALTHY_DEFAULTS.sentiment_avg_7d).toFixed(3),
    ),
    mood_avg_7d: Number(
      avg(moodValues, HEALTHY_DEFAULTS.mood_avg_7d).toFixed(2),
    ),
    sleep_avg_7d: Number(
      avg(sleepValues, HEALTHY_DEFAULTS.sleep_avg_7d).toFixed(2),
    ),
    journal_count_7d: journals.length,
    social_engagement_7d: Number(engagement.toFixed(3)),
  };
}
